version: '3.7'
services:
  db:
    image: restsql/mysql-sakila:latest
    restart: on-failure
    ports:
      - '3306:3306'
    expose:
      - '3306'
    command: mysqld --sql_mode="ONLY_FULL_GROUP_BY"
